use crate::utils::{EnvConfig, replace_yaml_content};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

pub async fn run(
    dir: String,
    env: String,
    output: Option<String>,
    map_file: String,
) -> Result<(), String> {
    let map_file_buf = PathBuf::from(&map_file);
    if !map_file_buf.exists() {
        return Err(format!("Mapping file not found: {:?}", map_file_buf));
    }

    let content = fs::read_to_string(&map_file_buf)
        .map_err(|e| format!("Failed to read mapping file {:?}: {}", map_file_buf, e))?;
    let mapping: HashMap<String, EnvConfig> = serde_json::from_str(&content)
        .map_err(|e| format!("Failed to parse mapping JSON in {:?}: {}", map_file_buf, e))?;

    let env_config = mapping.get(&env).ok_or_else(|| {
        format!(
            "Environment '{}' not found in mapping file {:?}",
            env, map_file_buf
        )
    })?;

    let empty_rules = Vec::new();
    let rules = match &env_config.replace_rules {
        Some(r) if !r.is_empty() => r,
        _ => {
            println!(
                "[!] Warning: Environment '{}' has no replace_rules defined in mapping file. Output will be generated without replacement.",
                env
            );
            &empty_rules
        }
    };

    let input_dir = Path::new(&dir);
    if !input_dir.exists() || !input_dir.is_dir() {
        return Err(format!(
            "Input directory not found or is not a directory: {}",
            dir
        ));
    }

    let env_keys: Vec<String> = mapping.keys().cloned().collect();

    println!(
        "[*] Replacing DSL content for env '{}' (rules: {}) from directory '{}'...",
        env,
        rules.len(),
        dir
    );

    let mut count = 0;
    for entry in WalkDir::new(input_dir).into_iter().filter_map(|e| e.ok()) {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }

        let rel_path = match path.strip_prefix(input_dir) {
            Ok(p) => p,
            Err(_) => continue,
        };

        // Skip files inside directories generated by previous replace runs (e.g. workflows-production)
        if let Some(first_comp) = rel_path.components().next() {
            let first_str = first_comp.as_os_str().to_string_lossy();
            if env_keys
                .iter()
                .any(|k| first_str.ends_with(&format!("-{}", k)))
            {
                continue;
            }
        }

        // Only process .yml and .yaml files
        let ext = path.extension().and_then(|s| s.to_str()).unwrap_or("");
        if ext != "yml" && ext != "yaml" {
            continue;
        }

        let target_path = calculate_target_path(input_dir, rel_path, &env, output.as_deref());

        let yaml_content = fs::read_to_string(path)
            .map_err(|e| format!("Failed to read file {:?}: {}", path, e))?;

        let replaced_yaml = replace_yaml_content(&yaml_content, rules)
            .map_err(|e| format!("Failed to replace content for file {:?}: {}", path, e))?;

        if let Some(parent) = target_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|e| format!("Failed to create directory {:?}: {}", parent, e))?;
        }

        fs::write(&target_path, replaced_yaml)
            .map_err(|e| format!("Failed to write file {:?}: {}", target_path, e))?;

        println!("  [+] {:?} -> {:?}", path, target_path);
        count += 1;
    }

    println!(
        "[✓] Successfully processed and output {} DSL file(s).",
        count
    );
    Ok(())
}

fn calculate_target_path(
    input_dir: &Path,
    rel_path: &Path,
    env: &str,
    custom_output: Option<&str>,
) -> PathBuf {
    if let Some(out_root) = custom_output {
        Path::new(out_root).join(rel_path)
    } else {
        let mut components = rel_path.components();
        if let Some(first_comp) = components.next() {
            let first_str = first_comp.as_os_str().to_string_lossy();
            if components.as_path().as_os_str().is_empty() {
                // File is directly inside input_dir (e.g. input_dir/app.yml)
                let stem = Path::new(&*first_str)
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap_or(&first_str);
                let ext = Path::new(&*first_str)
                    .extension()
                    .and_then(|s| s.to_str())
                    .unwrap_or("yml");
                let new_filename = format!("{}-{}.{}", stem, env, ext);
                input_dir.join(new_filename)
            } else {
                // File is inside a subdirectory (e.g. input_dir/workflows/app.yml)
                let new_subdir = format!("{}-{}", first_str, env);
                input_dir.join(new_subdir).join(components.as_path())
            }
        } else {
            input_dir.join(rel_path)
        }
    }
}
